import type { Metadata } from "next";
import { SectionRule } from "@tycoonhood/ui";

export const metadata: Metadata = {
  title: "Credits",
  description: "The third-party assets in the Tycoonhood HQ, who made them, and under what licence.",
};

/**
 * Attribution for third-party assets in the 3D HQ. CC BY 4.0 requires it;
 * the copyright lines are copied from each file's embedded `asset.copyright`,
 * not paraphrased. Mirrors apps/web/public/world/CREDITS.md — change both.
 */
const ASSETS: { name: string; use: string; credit: string; licence: string; licenceHref: string; source: string; sourceHref: string }[] = [
  {
    name: "Glam Velvet Sofa",
    use: "Lounge seating in the HQ interiors",
    credit: "© 2021 Wayfair",
    licence: "CC BY 4.0",
    licenceHref: "https://creativecommons.org/licenses/by/4.0/",
    source: "Khronos glTF Sample Assets",
    sourceHref: "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/GlamVelvetSofa",
  },
  {
    name: "Chair Damask Purplegold",
    use: "Armchairs in the HQ interiors",
    credit: "© 2021 Wayfair — created by Eric Chadwick",
    licence: "CC BY 4.0",
    licenceHref: "https://creativecommons.org/licenses/by/4.0/",
    source: "Khronos glTF Sample Assets",
    sourceHref: "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChairDamaskPurplegold",
  },
  {
    name: "Venice Sunset (HDRI)",
    use: "Reflections on the campus at dusk",
    credit: "Poly Haven",
    licence: "CC0",
    licenceHref: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Poly Haven, via the three.js examples",
    sourceHref: "https://polyhaven.com/a/venice_sunset",
  },
  {
    name: "Moonless Golf (HDRI)",
    use: "Night-time reflections",
    credit: "Poly Haven",
    licence: "CC0",
    licenceHref: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "Poly Haven, via the three.js examples",
    sourceHref: "https://polyhaven.com/a/moonless_golf",
  },
];

const link = "text-gold underline decoration-gold-shadow underline-offset-4 hover:decoration-gold";

export default function CreditsPage() {
  return (
    <main className="mx-auto max-w-3xl px-[var(--gutter)] py-16 md:py-24">
      <p className="eyebrow mb-3">The house</p>
      <h1 className="display text-h1">Credits</h1>
      <p className="mt-3 max-w-xl text-[15px] leading-relaxed text-ink-2">
        The HQ is built almost entirely in-house: the architecture, the stone, brass, oak and hedge
        materials, and the facades are all generated by our own code. The few things we did not make
        are listed here, with the people who did.
      </p>

      <SectionRule className="my-10" />

      <ul className="flex flex-col divide-y divide-line">
        {ASSETS.map((a) => (
          <li key={a.name} className="grid gap-1 py-5 sm:grid-cols-[1fr_auto] sm:gap-6">
            <div>
              <h2 className="display text-[19px] leading-snug">{a.name}</h2>
              <p className="mt-1 text-[14px] text-ink-2">{a.credit}</p>
              <p className="mt-1 text-[13px] text-ink-3">
                {a.use} ·{" "}
                <a href={a.sourceHref} className={link} rel="noopener noreferrer">
                  {a.source}
                </a>
              </p>
            </div>
            <p className="text-[13px] sm:text-right">
              <a href={a.licenceHref} className={link} rel="license noopener noreferrer">
                {a.licence}
              </a>
            </p>
          </li>
        ))}
      </ul>

      <SectionRule className="my-10" />
      <p className="text-[13px] leading-relaxed text-ink-3">
        The models are used unmodified. Type is set in fonts licensed under the SIL Open Font
        License. If you made something here and the credit is wrong or missing, tell us and we will
        correct it.
      </p>
    </main>
  );
}
